# https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/values.yaml
k8s-monitoring:
  cluster:
    name: my-cluster
  clusterMetrics:
    enabled: true
    kepler:
      enabled: false
    node-exporter:  # linux nodes, covered by kube-prom-stack
      enabled: false
      deploy: false
    kube-state-metrics:
      enabled: false
      deploy: false
    windows-exporter:
      enabled: false
      deploy: false
    opencost:
      enabled: true
      metricsSource: prometheus
      service:
        labels:
          release: ${release_name}
      # https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml
      opencost:
        exporter:
          defaultClusterId: my-cluster
        metrics:
          serviceMonitor:
            enabled: true
            additionalLabels:
              release: ${release_name}
        prometheus:
          external:
            enabled: true
            url: http://${release_name}-kube-prom-stack-prometheus:9090
        
  clusterEvents:
    enabled: true
  nodeLogs:
    enabled: true
  podLogs:
    enabled: true
  alloy-metrics:
    enabled: true
    alloy:
      resources:
        requests:
          cpu: 20m
          memory: 650Mi
        limits:
          cpu: 300m
          memory: 2Gi
  alloy-singleton:
    enabled: true
    alloy:
      resources:
        requests:
          cpu: 10m
          memory: 60Mi
        limits:
          cpu: 20m
          memory: 100Mi
  alloy-logs:
    enabled: true
    alloy:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          cpu: 20m
          memory: 150Mi
  alloy-profiles:
    enabled: false
  alloy-receiver:
    enabled: true
    alloy:
      extraPorts:
        - name: faro
          port: 12347
          targetPort: 12347
          protocol: TCP
        - name: otlp-grpc
          port: 4317
          targetPort: 4317
          protocol: TCP
        - name: otlp-http
          port: 4318
          targetPort: 4318
          protocol: TCP
        # - name: profiles
        #   port: 4040
        #   targetPort: 4040
        #   protocol: TCP
  applicationObservability:
    enabled: true
    receivers:
      faro:
        enabled: true
      otlp:
        enabled: true
        grpc:
          enabled: true
  autoInstrumentation:
    enabled: true
  annotationAutodiscovery:
    enabled: true
  prometheusOperatorObjects:
    enabled: false
  profiling:
    enabled: false
    ebpf:
      enabled: true  # can be set to true if pyroscope is disabled
  profilesReceiver:
    enabled: false
  destinations:
    - name: prometheus
      type: prometheus
      url: http://${release_name}-kube-prom-stack-prometheus:9090/api/v1/write
    - name: loki
      type: loki
      url: http://${release_name}-loki-gateway/loki/api/v1/push
    - name: tempo
      type: otlp
      url: http://${release_name}-tempo:4317
      traces:
        enabled: true
    # - name: pyroscope
    #   type: pyroscope
    #   url: http://${release_name}-pyroscope:4040
  alerting:
    enabled: true
    alertmanager:
      host: http://${release_name}-kube-prom-stack-alertmanager:9093

# https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
loki:
  enabled: true
  deploymentMode: SingleBinary
  resultsCache:
    enabled: false
  chunksCache:
    enabled: false
  test:  # if test is enabled, lokiCanary has to be enabled as well
    enabled: false
  lokiCanary:
    enabled: false
  loki:
    auth_enabled: false
    structuredConfig:
      common:
        replication_factor: 1
        ring:
          instance_addr: 127.0.0.1
          kvstore:
            store: inmemory
      ingester:
        lifecycler:
          ring:
            replication_factor: 1
            kvstore:
              store: inmemory
      memberlist:
        join_members: []
    storage:
      type: filesystem
    compactor:
      retention_enabled: true
      delete_request_store: filesystem
      working_directory: /var/loki/retention
    schemaConfig:
      configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  singleBinary:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: ""
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 100Mi
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0

# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prom-stack/values.yaml
kube-prom-stack:
  crds:
    enabled: true
    upgradeJob:
      enabled: true
      forceConflicts: true
  nodeExporter:
    enabled: true
    operatingSystems:
      linux:
        enabled: true
      aix:
        enabled: false
      darwin:
        enabled: false
  grafana:
    enabled: true
    initChownData:
      enabled: false
    defaultDashboardsEnabled: true
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      hosts:
      - monitoring.ludicdrive.com
      tls:
      - hosts:
        - monitoring.ludicdrive.com
        secretName: monitoring.ludicdrive.com-tls
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: ""
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        searchNamespace: ALL
      datasources:
        enabled: true
        name: Prometheus
        uid: prometheus
        extraJsonData:
          annotations:
          - name: "Alerting Events"
            datasource: "Prometheus"
            enable: true
            iconColor: "#ff0000"
            expr: 'ALERTS{alertstate="firing"}'
            step: "1m"
            textField: "alertname"
          - name: "Flux Deployments"
            datasource: "Prometheus"
            enable: true
            iconColor: "#00ff00"
            expr: 'gotk_reconcile_condition{status="True",type="Ready"}'
            textField: "name"
        alertmanager:
          enabled: true
          name: Alertmanager
          uid: alertmanager
          handleGrafanaManagedAlerts: false
          implementation: prometheus
    additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      orgId: 1
      url: http://{{ .Release.Name }}-loki-gateway
      access: proxy
      jsonData:
        derivedFields:
          - datasourceUid: tempo # must match UID of tempo datasource
            matcherRegex: "trace_id=(\\w+)" # looks for trace_id=xyz in the logs
            name: TraceID
            url: '$${__value.raw}'
    - name: Tempo
      type: tempo
      uid: tempo
      orgId: 1
      url: http://{{ .Release.Name }}-tempo:3200
      access: proxy
      jsonData:
        serviceMap:
          datasourceUid: prometheus
        nodeGraph:
          enabled: true
    # - name: Pyroscope
    #   type: phlare
    #   uid: pyroscope
    #   orgId: 1
    #   url: http://{{ .Release.Name }}-pyroscope:4040
    #   access: proxy
    grafana.ini:
      dashboards:
        default_home_dashboard_path: /tmp/dashboards/alert-history.json
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
          - name: 'apps'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/apps
          - name: 'cost-management'
            orgId: 1
            folder: 'cost-management'
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/cost-management
    dashboards:
      default:
        blackbox-exporter:
          gnetId: 13659
          revision: 1
          datasource: prometheus
      cost-management:
        opencost-overview:
          gnetId: 22208
          revision: 4
          datasource: prometheus
        opencost-namespace:
          gnetId: 22252
          revision: 5
          datasource: prometheus
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 100Mi
  prometheus:
    prometheusSpec:
      externalLabels:
        cluster: "my-cluster"  # must match value of k8s-monitoring.cluster.name
      enableRemoteWriteReceiver: true
    resources:
      limits: 
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 100Mi
    server:
      retention: 14d
      persistentVolume:
        size: 20Gi
      extraFlags:
        - web.enable-remote-write-receiver
    prometheus-windows-exporter:
      prometheus:
        monitor:
          enabled: false
  alertmanager:
    enabled: true
    prometheusOperator:
      tls:
        enabled: false
    alertmanagerSpec:
      web: {}
      tlsConfig: {}
      secrets:
        - slack-config
    config:
      global:
        resolve_timeout: 5m
        slack_api_url_file: '/etc/alertmanager/secrets/slack-config/slackWebhookUrl'
      route:
        group_by: ['alertname', 'job']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'slack-notifications'
        routes:
          # - receiver: 'alertsnitch'
          #   continue: true
          - receiver: 'slack-notifications'
            matchers:
              - severity = critical
      receivers:
      # - name: 'alertsnitch'
      #   webhook_configs:
      #   - url: 'http://alertsnitch:9567/webhook'
      #     send_resolved: true
      - name: 'slack-notifications'
        slack_configs:
          - channel: '#k8s-ops'
            send_resolved: true
            actions:
              - type: button
                text: '📈 View Dashboard'
                url: 'https://monitoring.ludicdrive.com/d/alert-history?var-alertname={{ .GroupLabels.alertname }}&from={{ (index .Alerts 0).StartsAt.Unix }}000&to=now'

# https://github.com/grafana-community/helm-charts/blob/main/charts/tempo/values.yaml
tempo:
  enabled: true
  tempo:
    reportingEnabled: false
    retention: 336h 
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        wal:
          path: /var/tempo/wal
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    metricsGenerator:
      # -- If true, enables Tempo's metrics generator (https://grafana.com/docs/tempo/next/metrics-generator/)
      enabled: true
      remoteWriteUrl: "http://${release_name}-kube-prom-stack-prometheus:9090/api/v1/write"
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
  persistence:
    enabled: true
    size: 50Gi
    storageClassName: ""

# https://github.com/grafana/pyroscope/blob/main/operations/pyroscope/helm/pyroscope/values.yaml
pyroscope:
  enabled: false
  pyroscope:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi

# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/values.yaml
prometheus-blackbox-exporter:
  enabled: true
  defaults:
    module: http_success
  config:
    modules:
      http_success:
        prober: http
        timeout: 5s
        http:
          method: GET
          valid_status_codes: [200, 201, 302, 403] 
          follow_redirects: true
          preferred_ip_protocol: "ip4"

blackboxProbeTargets:
  - https://example.com
  - https://another.example.com

alertsnitch:
  enabled: false
